### PR TITLE
Adding NLS feature

### PR DESCRIPTION
**Pull request by VinceAxe**
Proposition to add NLS component in order to translate more efficiently the pluggin

### CODE REVIEW

**Comment by Phillipus** [comment]
Hi, thanks for this. However, because we're working on some new features in the "branching" development branch, some of the language strings are going to be reconfigured and will change. Also it's on my TODO list to consolidate some of them. So, I suggest:

- Wait until the "branching" branch is merged into master and assess what Strings needs changing then
- Submit the NLS project in a separate PR so that it's an Eclipse project here (no need to go in "other" folder.

**Comment by VinceAxe** [comment]
No problem about waiting, it was also a way to save the work
The "other" folder was to be aligned with the Archi way to treat NLS

**Comment by Phillipus** [comment]
> No problem about waiting, it was also a way to save the work
The "other" folder was to be aligned with the Archi way to treat NLS

Yes, I thought so. I could see you thought about it. Thank-you. :-)

If you don't mind I'll "reject" this PR, and when the new development work is completed we can come back to what needs doing on NLS.

**Comment by Phillipus** [comment]
On hold, come back to it later! :-)

**Pull request closed without merging**
